# Generated by Django 3.2.18 on 2023-03-26 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdm', '0002_auto_20230322_2117'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='texte',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
