# Generated by Django 3.2.18 on 2023-03-26 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fdm', '0003_article_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='texte',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
