# Generated by Django 3.2.18 on 2023-03-26 13:04

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdm', '0004_alter_article_texte'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='texte',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
