# Generated by Django 3.2.18 on 2023-03-28 11:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fdm', '0006_alter_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='texte',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
